begin;

create table if not exists public.data_export_consent (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete restrict,
  export_kind text not null check (export_kind in ('view', 'csv', 'xlsx', 'pdf')),
  resource text not null,
  policy_version text not null,
  context jsonb not null default '{}'::jsonb,
  accepted_at timestamptz not null default now()
);

create index if not exists data_export_consent_user_date_idx
  on public.data_export_consent (user_id, accepted_at desc);
create index if not exists data_export_consent_resource_date_idx
  on public.data_export_consent (resource, accepted_at desc);

alter table public.data_export_consent enable row level security;
revoke insert, update, delete on public.data_export_consent from anon, authenticated;
grant select on public.data_export_consent to authenticated;

drop policy if exists data_export_consent_read_authorized on public.data_export_consent;
create policy data_export_consent_read_authorized
on public.data_export_consent for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role in ('admin', 'jefe_area', 'director')
  )
);

create or replace function public.record_data_export_consent(
  p_export_kind text,
  p_resource text,
  p_policy_version text,
  p_context jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if auth.uid() is null then
    raise exception 'Sesion requerida' using errcode = '42501';
  end if;
  if p_export_kind not in ('view', 'csv', 'xlsx', 'pdf') then
    raise exception 'Tipo de exportacion invalido';
  end if;
  if length(trim(coalesce(p_resource, ''))) = 0 or length(p_resource) > 120 then
    raise exception 'Recurso de exportacion invalido';
  end if;
  if length(trim(coalesce(p_policy_version, ''))) = 0 or length(p_policy_version) > 80 then
    raise exception 'Version de aviso invalida';
  end if;
  if pg_column_size(coalesce(p_context, '{}'::jsonb)) > 8192 then
    raise exception 'Contexto de consentimiento demasiado grande';
  end if;

  insert into public.data_export_consent (user_id, export_kind, resource, policy_version, context)
  values (auth.uid(), p_export_kind, trim(p_resource), trim(p_policy_version), coalesce(p_context, '{}'::jsonb))
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.record_data_export_consent(text, text, text, jsonb) from public, anon;
grant execute on function public.record_data_export_consent(text, text, text, jsonb) to authenticated;

commit;
